### ISSUE TITLE
Language selected on first launch not taken into account

### ISSUE THREAD

**Issue by hectorticoli** [chelh/VBASync#26]
Hi chelh,

With the following scenario, language is not correctly taken into account:
- First launch of VBASync, portable version
- Keep all options as default, and click Apply, then OK
- Quit VBASync with the cross button

The LastSession.ini file is as follow
[LastSession.ini.txt](https://github.com/chelh/VBASync/files/966801/LastSession.ini.txt)

You can see that Language field is empty.
As a result, on my french OS, when I wanted to keep "english" for screenshots, the default french language was used.

=> Maybe, if possible, set the Language value as the OS language if available (but definitely not mandatory)

Thank you very much, and sorry for reporting so many issues today :-)

**Comment by chelh** [comment]
Here's a v2.1.2 release candidate for you to test! It should also address #20, #23, #24, and #25. Full list of changes:

 * **Breaking change:** Since v1.x the program's name has changed. If you have shortcuts that point to `VBA Sync Tool.exe`, point them at `VBASync.exe` instead!
 * VBA Sync Tool can now manage your VBA project's license keys, if it has any
 * Allow dragging and dropping files
 * Automatically switch file and folder paths if needed
 * Added validation to file and folder boxes
 * Added clickable hyperlinks to the About window
 * Added edit menu
 * Added session option to ignore empty files
 * Added session option to add new document modules when publishing (now off by default)
 * Added keyboard shortcut for save session (<kbd>Ctrl</kbd>+<kbd>S</kbd>)
 * Added keyboard shortcut for open session (<kbd>Ctrl</kbd>+<kbd>O</kbd>)
 * Added keyboard shortcut for load last session (<kbd>Ctrl</kbd>+<kbd>L</kbd>)
 * Bug fix: Installer was leaving around old `VBA Sync Tool.exe`
 * Bug fix: Recent files list wasn't being loaded
 * Bug fix: `Project.ini` was being saved without an ending newline

[Portable VBA Sync Tool 2.1.2.zip](https://github.com/chelh/VBASync/files/969256/Portable.VBA.Sync.Tool.2.1.2.zip)

**Comment by hectorticoli** [comment]
Hi chelh,

2.1.2 is OK for this issue ^^
